command: [
  "flask",
  "--app",
  "app.py",
  "run"
]

env:
  - name: LAKEBASE_SECRET_SCOPE
    value: "database"
  - name: LAKEBASE_URL
    value: "lakebase-url"
  - name: MASSIVE_API_BASE_URL
    value: "https://api.massive.example.com"
  - name: MASSIVE_SECRET_SCOPE
    value: "massive"
  - name: MASSIVE_SECRET_KEY
    value: "api-key"
